"""empty message

Revision ID: 0f09ae1d356c
Revises: d663775be833
Create Date: 2020-05-22 22:50:59.817351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f09ae1d356c'
down_revision = 'd663775be833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'num')
    # ### end Alembic commands ###
